class MyOwnException(Exception):
    pass

raise MyOwnException('Это моя ошибка!')